package rfm.qd.repository.model;

import java.util.Date;

public class BiAccChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.PK_ID
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.DETAIL_ID
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.TRADE_TYPE
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.REMARK
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.NOTIFY_ID
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.GET_FLAG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String getFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.GET_NUM
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private Integer getNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.GET_MSG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String getMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.DELETED_FLAG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.ORIGIN_FLAG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.ORIGIN_APP
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String originApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.CREATED_BY
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.CREATED_DATE
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.LAST_UPD_BY
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.LAST_UPD_DATE
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.BI_ACC_CHANGE.MODIFICATION_NUM
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    private String modificationNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.PK_ID
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.PK_ID
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.PK_ID
     *
     * @param pkId the value for BRZFDC.BI_ACC_CHANGE.PK_ID
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setPkId(String pkId) {
        this.pkId = pkId == null ? null : pkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.DETAIL_ID
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.DETAIL_ID
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.DETAIL_ID
     *
     * @param detailId the value for BRZFDC.BI_ACC_CHANGE.DETAIL_ID
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setDetailId(String detailId) {
        this.detailId = detailId == null ? null : detailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.TRADE_TYPE
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.TRADE_TYPE
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.TRADE_TYPE
     *
     * @param tradeType the value for BRZFDC.BI_ACC_CHANGE.TRADE_TYPE
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.REMARK
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.REMARK
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.REMARK
     *
     * @param remark the value for BRZFDC.BI_ACC_CHANGE.REMARK
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.NOTIFY_ID
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.NOTIFY_ID
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.NOTIFY_ID
     *
     * @param notifyId the value for BRZFDC.BI_ACC_CHANGE.NOTIFY_ID
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId == null ? null : notifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.GET_FLAG
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.GET_FLAG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getGetFlag() {
        return getFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.GET_FLAG
     *
     * @param getFlag the value for BRZFDC.BI_ACC_CHANGE.GET_FLAG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setGetFlag(String getFlag) {
        this.getFlag = getFlag == null ? null : getFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.GET_NUM
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.GET_NUM
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public Integer getGetNum() {
        return getNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.GET_NUM
     *
     * @param getNum the value for BRZFDC.BI_ACC_CHANGE.GET_NUM
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setGetNum(Integer getNum) {
        this.getNum = getNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.GET_MSG
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.GET_MSG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getGetMsg() {
        return getMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.GET_MSG
     *
     * @param getMsg the value for BRZFDC.BI_ACC_CHANGE.GET_MSG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setGetMsg(String getMsg) {
        this.getMsg = getMsg == null ? null : getMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.DELETED_FLAG
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.DELETED_FLAG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.DELETED_FLAG
     *
     * @param deletedFlag the value for BRZFDC.BI_ACC_CHANGE.DELETED_FLAG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.ORIGIN_FLAG
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.ORIGIN_FLAG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.ORIGIN_FLAG
     *
     * @param originFlag the value for BRZFDC.BI_ACC_CHANGE.ORIGIN_FLAG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.ORIGIN_APP
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.ORIGIN_APP
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getOriginApp() {
        return originApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.ORIGIN_APP
     *
     * @param originApp the value for BRZFDC.BI_ACC_CHANGE.ORIGIN_APP
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setOriginApp(String originApp) {
        this.originApp = originApp == null ? null : originApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.CREATED_BY
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.CREATED_BY
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.CREATED_BY
     *
     * @param createdBy the value for BRZFDC.BI_ACC_CHANGE.CREATED_BY
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.CREATED_DATE
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.CREATED_DATE
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.CREATED_DATE
     *
     * @param createdDate the value for BRZFDC.BI_ACC_CHANGE.CREATED_DATE
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.LAST_UPD_BY
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.LAST_UPD_BY
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.LAST_UPD_BY
     *
     * @param lastUpdBy the value for BRZFDC.BI_ACC_CHANGE.LAST_UPD_BY
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.LAST_UPD_DATE
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.LAST_UPD_DATE
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for BRZFDC.BI_ACC_CHANGE.LAST_UPD_DATE
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.BI_ACC_CHANGE.MODIFICATION_NUM
     *
     * @return the value of BRZFDC.BI_ACC_CHANGE.MODIFICATION_NUM
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.BI_ACC_CHANGE.MODIFICATION_NUM
     *
     * @param modificationNum the value for BRZFDC.BI_ACC_CHANGE.MODIFICATION_NUM
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setModificationNum(String modificationNum) {
        this.modificationNum = modificationNum == null ? null : modificationNum.trim();
    }
}