package rfm.qd.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BiAccountDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public BiAccountDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkIdIsNull() {
            addCriterion("PK_ID is null");
            return (Criteria) this;
        }

        public Criteria andPkIdIsNotNull() {
            addCriterion("PK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPkIdEqualTo(String value) {
            addCriterion("PK_ID =", value, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdNotEqualTo(String value) {
            addCriterion("PK_ID <>", value, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdGreaterThan(String value) {
            addCriterion("PK_ID >", value, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdGreaterThanOrEqualTo(String value) {
            addCriterion("PK_ID >=", value, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdLessThan(String value) {
            addCriterion("PK_ID <", value, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdLessThanOrEqualTo(String value) {
            addCriterion("PK_ID <=", value, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdLike(String value) {
            addCriterion("PK_ID like", value, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdNotLike(String value) {
            addCriterion("PK_ID not like", value, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdIn(List<String> values) {
            addCriterion("PK_ID in", values, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdNotIn(List<String> values) {
            addCriterion("PK_ID not in", values, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdBetween(String value1, String value2) {
            addCriterion("PK_ID between", value1, value2, "pkId");
            return (Criteria) this;
        }

        public Criteria andPkIdNotBetween(String value1, String value2) {
            addCriterion("PK_ID not between", value1, value2, "pkId");
            return (Criteria) this;
        }

        public Criteria andAccountCodeIsNull() {
            addCriterion("ACCOUNT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAccountCodeIsNotNull() {
            addCriterion("ACCOUNT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAccountCodeEqualTo(String value) {
            addCriterion("ACCOUNT_CODE =", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeNotEqualTo(String value) {
            addCriterion("ACCOUNT_CODE <>", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeGreaterThan(String value) {
            addCriterion("ACCOUNT_CODE >", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_CODE >=", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeLessThan(String value) {
            addCriterion("ACCOUNT_CODE <", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_CODE <=", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeLike(String value) {
            addCriterion("ACCOUNT_CODE like", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeNotLike(String value) {
            addCriterion("ACCOUNT_CODE not like", value, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeIn(List<String> values) {
            addCriterion("ACCOUNT_CODE in", values, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeNotIn(List<String> values) {
            addCriterion("ACCOUNT_CODE not in", values, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeBetween(String value1, String value2) {
            addCriterion("ACCOUNT_CODE between", value1, value2, "accountCode");
            return (Criteria) this;
        }

        public Criteria andAccountCodeNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT_CODE not between", value1, value2, "accountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeIsNull() {
            addCriterion("TO_ACCOUNT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeIsNotNull() {
            addCriterion("TO_ACCOUNT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeEqualTo(String value) {
            addCriterion("TO_ACCOUNT_CODE =", value, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeNotEqualTo(String value) {
            addCriterion("TO_ACCOUNT_CODE <>", value, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeGreaterThan(String value) {
            addCriterion("TO_ACCOUNT_CODE >", value, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TO_ACCOUNT_CODE >=", value, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeLessThan(String value) {
            addCriterion("TO_ACCOUNT_CODE <", value, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeLessThanOrEqualTo(String value) {
            addCriterion("TO_ACCOUNT_CODE <=", value, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeLike(String value) {
            addCriterion("TO_ACCOUNT_CODE like", value, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeNotLike(String value) {
            addCriterion("TO_ACCOUNT_CODE not like", value, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeIn(List<String> values) {
            addCriterion("TO_ACCOUNT_CODE in", values, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeNotIn(List<String> values) {
            addCriterion("TO_ACCOUNT_CODE not in", values, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeBetween(String value1, String value2) {
            addCriterion("TO_ACCOUNT_CODE between", value1, value2, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andToAccountCodeNotBetween(String value1, String value2) {
            addCriterion("TO_ACCOUNT_CODE not between", value1, value2, "toAccountCode");
            return (Criteria) this;
        }

        public Criteria andInoutFlagIsNull() {
            addCriterion("INOUT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andInoutFlagIsNotNull() {
            addCriterion("INOUT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andInoutFlagEqualTo(String value) {
            addCriterion("INOUT_FLAG =", value, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagNotEqualTo(String value) {
            addCriterion("INOUT_FLAG <>", value, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagGreaterThan(String value) {
            addCriterion("INOUT_FLAG >", value, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagGreaterThanOrEqualTo(String value) {
            addCriterion("INOUT_FLAG >=", value, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagLessThan(String value) {
            addCriterion("INOUT_FLAG <", value, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagLessThanOrEqualTo(String value) {
            addCriterion("INOUT_FLAG <=", value, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagLike(String value) {
            addCriterion("INOUT_FLAG like", value, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagNotLike(String value) {
            addCriterion("INOUT_FLAG not like", value, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagIn(List<String> values) {
            addCriterion("INOUT_FLAG in", values, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagNotIn(List<String> values) {
            addCriterion("INOUT_FLAG not in", values, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagBetween(String value1, String value2) {
            addCriterion("INOUT_FLAG between", value1, value2, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andInoutFlagNotBetween(String value1, String value2) {
            addCriterion("INOUT_FLAG not between", value1, value2, "inoutFlag");
            return (Criteria) this;
        }

        public Criteria andTradeAmountIsNull() {
            addCriterion("TRADE_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountIsNotNull() {
            addCriterion("TRADE_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTradeAmountEqualTo(BigDecimal value) {
            addCriterion("TRADE_AMOUNT =", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountNotEqualTo(BigDecimal value) {
            addCriterion("TRADE_AMOUNT <>", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountGreaterThan(BigDecimal value) {
            addCriterion("TRADE_AMOUNT >", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRADE_AMOUNT >=", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLessThan(BigDecimal value) {
            addCriterion("TRADE_AMOUNT <", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRADE_AMOUNT <=", value, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountIn(List<BigDecimal> values) {
            addCriterion("TRADE_AMOUNT in", values, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountNotIn(List<BigDecimal> values) {
            addCriterion("TRADE_AMOUNT not in", values, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRADE_AMOUNT between", value1, value2, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andTradeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRADE_AMOUNT not between", value1, value2, "tradeAmount");
            return (Criteria) this;
        }

        public Criteria andSerialIsNull() {
            addCriterion("SERIAL is null");
            return (Criteria) this;
        }

        public Criteria andSerialIsNotNull() {
            addCriterion("SERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andSerialEqualTo(String value) {
            addCriterion("SERIAL =", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotEqualTo(String value) {
            addCriterion("SERIAL <>", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThan(String value) {
            addCriterion("SERIAL >", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThanOrEqualTo(String value) {
            addCriterion("SERIAL >=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThan(String value) {
            addCriterion("SERIAL <", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThanOrEqualTo(String value) {
            addCriterion("SERIAL <=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLike(String value) {
            addCriterion("SERIAL like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotLike(String value) {
            addCriterion("SERIAL not like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialIn(List<String> values) {
            addCriterion("SERIAL in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotIn(List<String> values) {
            addCriterion("SERIAL not in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialBetween(String value1, String value2) {
            addCriterion("SERIAL between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotBetween(String value1, String value2) {
            addCriterion("SERIAL not between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andBankSerialIsNull() {
            addCriterion("BANK_SERIAL is null");
            return (Criteria) this;
        }

        public Criteria andBankSerialIsNotNull() {
            addCriterion("BANK_SERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andBankSerialEqualTo(String value) {
            addCriterion("BANK_SERIAL =", value, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialNotEqualTo(String value) {
            addCriterion("BANK_SERIAL <>", value, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialGreaterThan(String value) {
            addCriterion("BANK_SERIAL >", value, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_SERIAL >=", value, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialLessThan(String value) {
            addCriterion("BANK_SERIAL <", value, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialLessThanOrEqualTo(String value) {
            addCriterion("BANK_SERIAL <=", value, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialLike(String value) {
            addCriterion("BANK_SERIAL like", value, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialNotLike(String value) {
            addCriterion("BANK_SERIAL not like", value, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialIn(List<String> values) {
            addCriterion("BANK_SERIAL in", values, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialNotIn(List<String> values) {
            addCriterion("BANK_SERIAL not in", values, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialBetween(String value1, String value2) {
            addCriterion("BANK_SERIAL between", value1, value2, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andBankSerialNotBetween(String value1, String value2) {
            addCriterion("BANK_SERIAL not between", value1, value2, "bankSerial");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNull() {
            addCriterion("TRADE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNotNull() {
            addCriterion("TRADE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeDateEqualTo(String value) {
            addCriterion("TRADE_DATE =", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotEqualTo(String value) {
            addCriterion("TRADE_DATE <>", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThan(String value) {
            addCriterion("TRADE_DATE >", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_DATE >=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThan(String value) {
            addCriterion("TRADE_DATE <", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThanOrEqualTo(String value) {
            addCriterion("TRADE_DATE <=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLike(String value) {
            addCriterion("TRADE_DATE like", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotLike(String value) {
            addCriterion("TRADE_DATE not like", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateIn(List<String> values) {
            addCriterion("TRADE_DATE in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotIn(List<String> values) {
            addCriterion("TRADE_DATE not in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateBetween(String value1, String value2) {
            addCriterion("TRADE_DATE between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotBetween(String value1, String value2) {
            addCriterion("TRADE_DATE not between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIsNull() {
            addCriterion("TRADE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIsNotNull() {
            addCriterion("TRADE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTimeEqualTo(String value) {
            addCriterion("TRADE_TIME =", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotEqualTo(String value) {
            addCriterion("TRADE_TIME <>", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeGreaterThan(String value) {
            addCriterion("TRADE_TIME >", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_TIME >=", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLessThan(String value) {
            addCriterion("TRADE_TIME <", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_TIME <=", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLike(String value) {
            addCriterion("TRADE_TIME like", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotLike(String value) {
            addCriterion("TRADE_TIME not like", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIn(List<String> values) {
            addCriterion("TRADE_TIME in", values, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotIn(List<String> values) {
            addCriterion("TRADE_TIME not in", values, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeBetween(String value1, String value2) {
            addCriterion("TRADE_TIME between", value1, value2, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotBetween(String value1, String value2) {
            addCriterion("TRADE_TIME not between", value1, value2, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNull() {
            addCriterion("TRADE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNotNull() {
            addCriterion("TRADE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeEqualTo(String value) {
            addCriterion("TRADE_TYPE =", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotEqualTo(String value) {
            addCriterion("TRADE_TYPE <>", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThan(String value) {
            addCriterion("TRADE_TYPE >", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_TYPE >=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThan(String value) {
            addCriterion("TRADE_TYPE <", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_TYPE <=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLike(String value) {
            addCriterion("TRADE_TYPE like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotLike(String value) {
            addCriterion("TRADE_TYPE not like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIn(List<String> values) {
            addCriterion("TRADE_TYPE in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotIn(List<String> values) {
            addCriterion("TRADE_TYPE not in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeBetween(String value1, String value2) {
            addCriterion("TRADE_TYPE between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotBetween(String value1, String value2) {
            addCriterion("TRADE_TYPE not between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andPurposeIsNull() {
            addCriterion("PURPOSE is null");
            return (Criteria) this;
        }

        public Criteria andPurposeIsNotNull() {
            addCriterion("PURPOSE is not null");
            return (Criteria) this;
        }

        public Criteria andPurposeEqualTo(String value) {
            addCriterion("PURPOSE =", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotEqualTo(String value) {
            addCriterion("PURPOSE <>", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeGreaterThan(String value) {
            addCriterion("PURPOSE >", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeGreaterThanOrEqualTo(String value) {
            addCriterion("PURPOSE >=", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeLessThan(String value) {
            addCriterion("PURPOSE <", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeLessThanOrEqualTo(String value) {
            addCriterion("PURPOSE <=", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeLike(String value) {
            addCriterion("PURPOSE like", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotLike(String value) {
            addCriterion("PURPOSE not like", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeIn(List<String> values) {
            addCriterion("PURPOSE in", values, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotIn(List<String> values) {
            addCriterion("PURPOSE not in", values, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeBetween(String value1, String value2) {
            addCriterion("PURPOSE between", value1, value2, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotBetween(String value1, String value2) {
            addCriterion("PURPOSE not between", value1, value2, "purpose");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagIsNull() {
            addCriterion("ECHECK_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagIsNotNull() {
            addCriterion("ECHECK_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagEqualTo(String value) {
            addCriterion("ECHECK_FLAG =", value, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagNotEqualTo(String value) {
            addCriterion("ECHECK_FLAG <>", value, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagGreaterThan(String value) {
            addCriterion("ECHECK_FLAG >", value, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ECHECK_FLAG >=", value, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagLessThan(String value) {
            addCriterion("ECHECK_FLAG <", value, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagLessThanOrEqualTo(String value) {
            addCriterion("ECHECK_FLAG <=", value, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagLike(String value) {
            addCriterion("ECHECK_FLAG like", value, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagNotLike(String value) {
            addCriterion("ECHECK_FLAG not like", value, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagIn(List<String> values) {
            addCriterion("ECHECK_FLAG in", values, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagNotIn(List<String> values) {
            addCriterion("ECHECK_FLAG not in", values, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagBetween(String value1, String value2) {
            addCriterion("ECHECK_FLAG between", value1, value2, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andEcheckFlagNotBetween(String value1, String value2) {
            addCriterion("ECHECK_FLAG not between", value1, value2, "echeckFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagIsNull() {
            addCriterion("CHANGE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andChangeFlagIsNotNull() {
            addCriterion("CHANGE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andChangeFlagEqualTo(String value) {
            addCriterion("CHANGE_FLAG =", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagNotEqualTo(String value) {
            addCriterion("CHANGE_FLAG <>", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagGreaterThan(String value) {
            addCriterion("CHANGE_FLAG >", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagGreaterThanOrEqualTo(String value) {
            addCriterion("CHANGE_FLAG >=", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagLessThan(String value) {
            addCriterion("CHANGE_FLAG <", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagLessThanOrEqualTo(String value) {
            addCriterion("CHANGE_FLAG <=", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagLike(String value) {
            addCriterion("CHANGE_FLAG like", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagNotLike(String value) {
            addCriterion("CHANGE_FLAG not like", value, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagIn(List<String> values) {
            addCriterion("CHANGE_FLAG in", values, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagNotIn(List<String> values) {
            addCriterion("CHANGE_FLAG not in", values, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagBetween(String value1, String value2) {
            addCriterion("CHANGE_FLAG between", value1, value2, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andChangeFlagNotBetween(String value1, String value2) {
            addCriterion("CHANGE_FLAG not between", value1, value2, "changeFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNull() {
            addCriterion("DELETED_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNotNull() {
            addCriterion("DELETED_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagEqualTo(String value) {
            addCriterion("DELETED_FLAG =", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotEqualTo(String value) {
            addCriterion("DELETED_FLAG <>", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThan(String value) {
            addCriterion("DELETED_FLAG >", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETED_FLAG >=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThan(String value) {
            addCriterion("DELETED_FLAG <", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThanOrEqualTo(String value) {
            addCriterion("DELETED_FLAG <=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLike(String value) {
            addCriterion("DELETED_FLAG like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotLike(String value) {
            addCriterion("DELETED_FLAG not like", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIn(List<String> values) {
            addCriterion("DELETED_FLAG in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotIn(List<String> values) {
            addCriterion("DELETED_FLAG not in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagBetween(String value1, String value2) {
            addCriterion("DELETED_FLAG between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotBetween(String value1, String value2) {
            addCriterion("DELETED_FLAG not between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagIsNull() {
            addCriterion("ORIGIN_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andOriginFlagIsNotNull() {
            addCriterion("ORIGIN_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andOriginFlagEqualTo(String value) {
            addCriterion("ORIGIN_FLAG =", value, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagNotEqualTo(String value) {
            addCriterion("ORIGIN_FLAG <>", value, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagGreaterThan(String value) {
            addCriterion("ORIGIN_FLAG >", value, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ORIGIN_FLAG >=", value, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagLessThan(String value) {
            addCriterion("ORIGIN_FLAG <", value, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagLessThanOrEqualTo(String value) {
            addCriterion("ORIGIN_FLAG <=", value, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagLike(String value) {
            addCriterion("ORIGIN_FLAG like", value, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagNotLike(String value) {
            addCriterion("ORIGIN_FLAG not like", value, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagIn(List<String> values) {
            addCriterion("ORIGIN_FLAG in", values, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagNotIn(List<String> values) {
            addCriterion("ORIGIN_FLAG not in", values, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagBetween(String value1, String value2) {
            addCriterion("ORIGIN_FLAG between", value1, value2, "originFlag");
            return (Criteria) this;
        }

        public Criteria andOriginFlagNotBetween(String value1, String value2) {
            addCriterion("ORIGIN_FLAG not between", value1, value2, "originFlag");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("CREATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("CREATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("CREATED_DATE =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("CREATED_DATE <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("CREATED_DATE >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("CREATED_DATE <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("CREATED_DATE in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("CREATED_DATE not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNull() {
            addCriterion("LAST_UPD_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNotNull() {
            addCriterion("LAST_UPD_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByEqualTo(String value) {
            addCriterion("LAST_UPD_BY =", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotEqualTo(String value) {
            addCriterion("LAST_UPD_BY <>", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThan(String value) {
            addCriterion("LAST_UPD_BY >", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY >=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThan(String value) {
            addCriterion("LAST_UPD_BY <", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY <=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLike(String value) {
            addCriterion("LAST_UPD_BY like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotLike(String value) {
            addCriterion("LAST_UPD_BY not like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIn(List<String> values) {
            addCriterion("LAST_UPD_BY in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotIn(List<String> values) {
            addCriterion("LAST_UPD_BY not in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY not between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIsNull() {
            addCriterion("LAST_UPD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIsNotNull() {
            addCriterion("LAST_UPD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE =", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE <>", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateGreaterThan(Date value) {
            addCriterion("LAST_UPD_DATE >", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE >=", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateLessThan(Date value) {
            addCriterion("LAST_UPD_DATE <", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_DATE <=", value, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateIn(List<Date> values) {
            addCriterion("LAST_UPD_DATE in", values, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotIn(List<Date> values) {
            addCriterion("LAST_UPD_DATE not in", values, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_DATE between", value1, value2, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_DATE not between", value1, value2, "lastUpdDate");
            return (Criteria) this;
        }

        public Criteria andModificationNumIsNull() {
            addCriterion("MODIFICATION_NUM is null");
            return (Criteria) this;
        }

        public Criteria andModificationNumIsNotNull() {
            addCriterion("MODIFICATION_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andModificationNumEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM =", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM <>", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumGreaterThan(Integer value) {
            addCriterion("MODIFICATION_NUM >", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM >=", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumLessThan(Integer value) {
            addCriterion("MODIFICATION_NUM <", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumLessThanOrEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM <=", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumIn(List<Integer> values) {
            addCriterion("MODIFICATION_NUM in", values, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotIn(List<Integer> values) {
            addCriterion("MODIFICATION_NUM not in", values, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumBetween(Integer value1, Integer value2) {
            addCriterion("MODIFICATION_NUM between", value1, value2, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotBetween(Integer value1, Integer value2) {
            addCriterion("MODIFICATION_NUM not between", value1, value2, "modificationNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 18:28:59 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}