package rfm.qd.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class QdBiAccountCheck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.ACCOUNT_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.TO_ACCOUNT_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String toAccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.TRADE_AMOUNT
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private BigDecimal tradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.SERIAL
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.BANK_SERIAL
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String bankSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.TRADE_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.TRADE_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String tradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.TRADE_TYPE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.PURPOSE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.DCHECK_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String dcheckFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.CHANGE_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String changeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.DELETED_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.ORIGIN_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_ACCOUNT_CHECK.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Integer modificationNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.PK_ID
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.PK_ID
     *
     * @param pkId the value for QD_BI_ACCOUNT_CHECK.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setPkId(String pkId) {
        this.pkId = pkId == null ? null : pkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.ACCOUNT_CODE
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.ACCOUNT_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.ACCOUNT_CODE
     *
     * @param accountCode the value for QD_BI_ACCOUNT_CHECK.ACCOUNT_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.TO_ACCOUNT_CODE
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.TO_ACCOUNT_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getToAccountCode() {
        return toAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.TO_ACCOUNT_CODE
     *
     * @param toAccountCode the value for QD_BI_ACCOUNT_CHECK.TO_ACCOUNT_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setToAccountCode(String toAccountCode) {
        this.toAccountCode = toAccountCode == null ? null : toAccountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.TRADE_AMOUNT
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.TRADE_AMOUNT
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.TRADE_AMOUNT
     *
     * @param tradeAmount the value for QD_BI_ACCOUNT_CHECK.TRADE_AMOUNT
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.SERIAL
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.SERIAL
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.SERIAL
     *
     * @param serial the value for QD_BI_ACCOUNT_CHECK.SERIAL
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.BANK_SERIAL
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.BANK_SERIAL
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getBankSerial() {
        return bankSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.BANK_SERIAL
     *
     * @param bankSerial the value for QD_BI_ACCOUNT_CHECK.BANK_SERIAL
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setBankSerial(String bankSerial) {
        this.bankSerial = bankSerial == null ? null : bankSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.TRADE_DATE
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.TRADE_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.TRADE_DATE
     *
     * @param tradeDate the value for QD_BI_ACCOUNT_CHECK.TRADE_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate == null ? null : tradeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.TRADE_TIME
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.TRADE_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.TRADE_TIME
     *
     * @param tradeTime the value for QD_BI_ACCOUNT_CHECK.TRADE_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setTradeTime(String tradeTime) {
        this.tradeTime = tradeTime == null ? null : tradeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.TRADE_TYPE
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.TRADE_TYPE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.TRADE_TYPE
     *
     * @param tradeType the value for QD_BI_ACCOUNT_CHECK.TRADE_TYPE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.PURPOSE
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.PURPOSE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.PURPOSE
     *
     * @param purpose the value for QD_BI_ACCOUNT_CHECK.PURPOSE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.REMARK
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.REMARK
     *
     * @param remark the value for QD_BI_ACCOUNT_CHECK.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.DCHECK_FLAG
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.DCHECK_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getDcheckFlag() {
        return dcheckFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.DCHECK_FLAG
     *
     * @param dcheckFlag the value for QD_BI_ACCOUNT_CHECK.DCHECK_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setDcheckFlag(String dcheckFlag) {
        this.dcheckFlag = dcheckFlag == null ? null : dcheckFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.CHANGE_FLAG
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.CHANGE_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getChangeFlag() {
        return changeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.CHANGE_FLAG
     *
     * @param changeFlag the value for QD_BI_ACCOUNT_CHECK.CHANGE_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setChangeFlag(String changeFlag) {
        this.changeFlag = changeFlag == null ? null : changeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.DELETED_FLAG
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.DELETED_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.DELETED_FLAG
     *
     * @param deletedFlag the value for QD_BI_ACCOUNT_CHECK.DELETED_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.ORIGIN_FLAG
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.ORIGIN_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.ORIGIN_FLAG
     *
     * @param originFlag the value for QD_BI_ACCOUNT_CHECK.ORIGIN_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.CREATED_BY
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.CREATED_BY
     *
     * @param createdBy the value for QD_BI_ACCOUNT_CHECK.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.CREATED_DATE
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.CREATED_DATE
     *
     * @param createdDate the value for QD_BI_ACCOUNT_CHECK.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.LAST_UPD_BY
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.LAST_UPD_BY
     *
     * @param lastUpdBy the value for QD_BI_ACCOUNT_CHECK.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.LAST_UPD_DATE
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for QD_BI_ACCOUNT_CHECK.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_ACCOUNT_CHECK.MODIFICATION_NUM
     *
     * @return the value of QD_BI_ACCOUNT_CHECK.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Integer getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_ACCOUNT_CHECK.MODIFICATION_NUM
     *
     * @param modificationNum the value for QD_BI_ACCOUNT_CHECK.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
}