package rfm.qd.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class QdBiContractClose {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.CONTRACT_NO
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.ACCOUNT_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.ACCOUNT_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.BUYER_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String buyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.BUYER_ACC_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String buyerAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.BUYER_BANK_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String buyerBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.BUYER_CERT_TYPE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String buyerCertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.BUYER_CERT_NO
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String buyerCertNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.TOTAL_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private BigDecimal totalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.TRANS_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private BigDecimal transAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.HOUSE_ADDRESS
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String houseAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.PURPOSE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.NOTIFY_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.GET_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String getFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.GET_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Integer getNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.GET_MSG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String getMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.DELETED_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.ORIGIN_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.ORIGIN_APP
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String originApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_CONTRACT_CLOSE.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Integer modificationNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.PK_ID
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.PK_ID
     *
     * @param pkId the value for QD_BI_CONTRACT_CLOSE.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setPkId(String pkId) {
        this.pkId = pkId == null ? null : pkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.CONTRACT_NO
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.CONTRACT_NO
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.CONTRACT_NO
     *
     * @param contractNo the value for QD_BI_CONTRACT_CLOSE.CONTRACT_NO
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.ACCOUNT_CODE
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.ACCOUNT_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.ACCOUNT_CODE
     *
     * @param accountCode the value for QD_BI_CONTRACT_CLOSE.ACCOUNT_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.ACCOUNT_NAME
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.ACCOUNT_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.ACCOUNT_NAME
     *
     * @param accountName the value for QD_BI_CONTRACT_CLOSE.ACCOUNT_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_NAME
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.BUYER_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_NAME
     *
     * @param buyerName the value for QD_BI_CONTRACT_CLOSE.BUYER_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_ACC_CODE
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.BUYER_ACC_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getBuyerAccCode() {
        return buyerAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_ACC_CODE
     *
     * @param buyerAccCode the value for QD_BI_CONTRACT_CLOSE.BUYER_ACC_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setBuyerAccCode(String buyerAccCode) {
        this.buyerAccCode = buyerAccCode == null ? null : buyerAccCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_BANK_NAME
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.BUYER_BANK_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getBuyerBankName() {
        return buyerBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_BANK_NAME
     *
     * @param buyerBankName the value for QD_BI_CONTRACT_CLOSE.BUYER_BANK_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setBuyerBankName(String buyerBankName) {
        this.buyerBankName = buyerBankName == null ? null : buyerBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_CERT_TYPE
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.BUYER_CERT_TYPE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getBuyerCertType() {
        return buyerCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_CERT_TYPE
     *
     * @param buyerCertType the value for QD_BI_CONTRACT_CLOSE.BUYER_CERT_TYPE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setBuyerCertType(String buyerCertType) {
        this.buyerCertType = buyerCertType == null ? null : buyerCertType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_CERT_NO
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.BUYER_CERT_NO
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getBuyerCertNo() {
        return buyerCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.BUYER_CERT_NO
     *
     * @param buyerCertNo the value for QD_BI_CONTRACT_CLOSE.BUYER_CERT_NO
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setBuyerCertNo(String buyerCertNo) {
        this.buyerCertNo = buyerCertNo == null ? null : buyerCertNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.TOTAL_AMT
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.TOTAL_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public BigDecimal getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.TOTAL_AMT
     *
     * @param totalAmt the value for QD_BI_CONTRACT_CLOSE.TOTAL_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setTotalAmt(BigDecimal totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.TRANS_AMT
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.TRANS_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public BigDecimal getTransAmt() {
        return transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.TRANS_AMT
     *
     * @param transAmt the value for QD_BI_CONTRACT_CLOSE.TRANS_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setTransAmt(BigDecimal transAmt) {
        this.transAmt = transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.HOUSE_ADDRESS
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.HOUSE_ADDRESS
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getHouseAddress() {
        return houseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.HOUSE_ADDRESS
     *
     * @param houseAddress the value for QD_BI_CONTRACT_CLOSE.HOUSE_ADDRESS
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setHouseAddress(String houseAddress) {
        this.houseAddress = houseAddress == null ? null : houseAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.PURPOSE
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.PURPOSE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.PURPOSE
     *
     * @param purpose the value for QD_BI_CONTRACT_CLOSE.PURPOSE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.REMARK
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.REMARK
     *
     * @param remark the value for QD_BI_CONTRACT_CLOSE.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.NOTIFY_ID
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.NOTIFY_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.NOTIFY_ID
     *
     * @param notifyId the value for QD_BI_CONTRACT_CLOSE.NOTIFY_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId == null ? null : notifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.GET_FLAG
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.GET_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getGetFlag() {
        return getFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.GET_FLAG
     *
     * @param getFlag the value for QD_BI_CONTRACT_CLOSE.GET_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setGetFlag(String getFlag) {
        this.getFlag = getFlag == null ? null : getFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.GET_NUM
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.GET_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Integer getGetNum() {
        return getNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.GET_NUM
     *
     * @param getNum the value for QD_BI_CONTRACT_CLOSE.GET_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setGetNum(Integer getNum) {
        this.getNum = getNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.GET_MSG
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.GET_MSG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getGetMsg() {
        return getMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.GET_MSG
     *
     * @param getMsg the value for QD_BI_CONTRACT_CLOSE.GET_MSG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setGetMsg(String getMsg) {
        this.getMsg = getMsg == null ? null : getMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.DELETED_FLAG
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.DELETED_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.DELETED_FLAG
     *
     * @param deletedFlag the value for QD_BI_CONTRACT_CLOSE.DELETED_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.ORIGIN_FLAG
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.ORIGIN_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.ORIGIN_FLAG
     *
     * @param originFlag the value for QD_BI_CONTRACT_CLOSE.ORIGIN_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.ORIGIN_APP
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.ORIGIN_APP
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getOriginApp() {
        return originApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.ORIGIN_APP
     *
     * @param originApp the value for QD_BI_CONTRACT_CLOSE.ORIGIN_APP
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setOriginApp(String originApp) {
        this.originApp = originApp == null ? null : originApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.CREATED_BY
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.CREATED_BY
     *
     * @param createdBy the value for QD_BI_CONTRACT_CLOSE.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.CREATED_DATE
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.CREATED_DATE
     *
     * @param createdDate the value for QD_BI_CONTRACT_CLOSE.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.LAST_UPD_BY
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.LAST_UPD_BY
     *
     * @param lastUpdBy the value for QD_BI_CONTRACT_CLOSE.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.LAST_UPD_DATE
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for QD_BI_CONTRACT_CLOSE.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_CONTRACT_CLOSE.MODIFICATION_NUM
     *
     * @return the value of QD_BI_CONTRACT_CLOSE.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Integer getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_CONTRACT_CLOSE.MODIFICATION_NUM
     *
     * @param modificationNum the value for QD_BI_CONTRACT_CLOSE.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
}