package rfm.qd.repository.model;

import java.util.Date;

public class QdBiNotifyConf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.TYPE_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.TYPE_DESC
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String typeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.IMPL_CLASS
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String implClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.DEAL_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Integer dealNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.INTERVAL_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Integer intervalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.DELETED_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.ORIGIN_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.ORIGIN_APP
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String originApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_BI_NOTIFY_CONF.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    private Integer modificationNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.PK_ID
     *
     * @return the value of QD_BI_NOTIFY_CONF.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.PK_ID
     *
     * @param pkId the value for QD_BI_NOTIFY_CONF.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setPkId(String pkId) {
        this.pkId = pkId == null ? null : pkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.TYPE_CODE
     *
     * @return the value of QD_BI_NOTIFY_CONF.TYPE_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.TYPE_CODE
     *
     * @param typeCode the value for QD_BI_NOTIFY_CONF.TYPE_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.TYPE_DESC
     *
     * @return the value of QD_BI_NOTIFY_CONF.TYPE_DESC
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.TYPE_DESC
     *
     * @param typeDesc the value for QD_BI_NOTIFY_CONF.TYPE_DESC
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc == null ? null : typeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.IMPL_CLASS
     *
     * @return the value of QD_BI_NOTIFY_CONF.IMPL_CLASS
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getImplClass() {
        return implClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.IMPL_CLASS
     *
     * @param implClass the value for QD_BI_NOTIFY_CONF.IMPL_CLASS
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setImplClass(String implClass) {
        this.implClass = implClass == null ? null : implClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.DEAL_NUM
     *
     * @return the value of QD_BI_NOTIFY_CONF.DEAL_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Integer getDealNum() {
        return dealNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.DEAL_NUM
     *
     * @param dealNum the value for QD_BI_NOTIFY_CONF.DEAL_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setDealNum(Integer dealNum) {
        this.dealNum = dealNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.INTERVAL_TIME
     *
     * @return the value of QD_BI_NOTIFY_CONF.INTERVAL_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Integer getIntervalTime() {
        return intervalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.INTERVAL_TIME
     *
     * @param intervalTime the value for QD_BI_NOTIFY_CONF.INTERVAL_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setIntervalTime(Integer intervalTime) {
        this.intervalTime = intervalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.REMARK
     *
     * @return the value of QD_BI_NOTIFY_CONF.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.REMARK
     *
     * @param remark the value for QD_BI_NOTIFY_CONF.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.DELETED_FLAG
     *
     * @return the value of QD_BI_NOTIFY_CONF.DELETED_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.DELETED_FLAG
     *
     * @param deletedFlag the value for QD_BI_NOTIFY_CONF.DELETED_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.ORIGIN_FLAG
     *
     * @return the value of QD_BI_NOTIFY_CONF.ORIGIN_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.ORIGIN_FLAG
     *
     * @param originFlag the value for QD_BI_NOTIFY_CONF.ORIGIN_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.ORIGIN_APP
     *
     * @return the value of QD_BI_NOTIFY_CONF.ORIGIN_APP
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getOriginApp() {
        return originApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.ORIGIN_APP
     *
     * @param originApp the value for QD_BI_NOTIFY_CONF.ORIGIN_APP
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setOriginApp(String originApp) {
        this.originApp = originApp == null ? null : originApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.CREATED_BY
     *
     * @return the value of QD_BI_NOTIFY_CONF.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.CREATED_BY
     *
     * @param createdBy the value for QD_BI_NOTIFY_CONF.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.CREATED_DATE
     *
     * @return the value of QD_BI_NOTIFY_CONF.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.CREATED_DATE
     *
     * @param createdDate the value for QD_BI_NOTIFY_CONF.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.LAST_UPD_BY
     *
     * @return the value of QD_BI_NOTIFY_CONF.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.LAST_UPD_BY
     *
     * @param lastUpdBy the value for QD_BI_NOTIFY_CONF.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.LAST_UPD_DATE
     *
     * @return the value of QD_BI_NOTIFY_CONF.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for QD_BI_NOTIFY_CONF.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_BI_NOTIFY_CONF.MODIFICATION_NUM
     *
     * @return the value of QD_BI_NOTIFY_CONF.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public Integer getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_BI_NOTIFY_CONF.MODIFICATION_NUM
     *
     * @param modificationNum the value for QD_BI_NOTIFY_CONF.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }
}