package rfm.qd.repository.model;

public class QdCbsAccTxn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.PKID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.BANK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.OPER_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.SERIAL_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.QRY_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String qryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.QRY_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String qryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.ACCOUNT_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.SEQ_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.DEBIT_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String debitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.CREDIT_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String creditAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.TXN_TYPE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String txnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.TXN_SERIAL_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String txnSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.SUMMARY_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String summaryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.TXN_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.TXN_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String txnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.SEND_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String sendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_CBS_ACC_TXN.ACCOUNT_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String accountName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.PKID
     *
     * @return the value of QD_CBS_ACC_TXN.PKID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.PKID
     *
     * @param pkid the value for QD_CBS_ACC_TXN.PKID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.BANK_ID
     *
     * @return the value of QD_CBS_ACC_TXN.BANK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.BANK_ID
     *
     * @param bankId the value for QD_CBS_ACC_TXN.BANK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.OPER_ID
     *
     * @return the value of QD_CBS_ACC_TXN.OPER_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.OPER_ID
     *
     * @param operId the value for QD_CBS_ACC_TXN.OPER_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.SERIAL_NO
     *
     * @return the value of QD_CBS_ACC_TXN.SERIAL_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.SERIAL_NO
     *
     * @param serialNo the value for QD_CBS_ACC_TXN.SERIAL_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.QRY_DATE
     *
     * @return the value of QD_CBS_ACC_TXN.QRY_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getQryDate() {
        return qryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.QRY_DATE
     *
     * @param qryDate the value for QD_CBS_ACC_TXN.QRY_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setQryDate(String qryDate) {
        this.qryDate = qryDate == null ? null : qryDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.QRY_TIME
     *
     * @return the value of QD_CBS_ACC_TXN.QRY_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getQryTime() {
        return qryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.QRY_TIME
     *
     * @param qryTime the value for QD_CBS_ACC_TXN.QRY_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setQryTime(String qryTime) {
        this.qryTime = qryTime == null ? null : qryTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.ACCOUNT_NO
     *
     * @return the value of QD_CBS_ACC_TXN.ACCOUNT_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.ACCOUNT_NO
     *
     * @param accountNo the value for QD_CBS_ACC_TXN.ACCOUNT_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.SEQ_NO
     *
     * @return the value of QD_CBS_ACC_TXN.SEQ_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.SEQ_NO
     *
     * @param seqNo the value for QD_CBS_ACC_TXN.SEQ_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.DEBIT_AMT
     *
     * @return the value of QD_CBS_ACC_TXN.DEBIT_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getDebitAmt() {
        return debitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.DEBIT_AMT
     *
     * @param debitAmt the value for QD_CBS_ACC_TXN.DEBIT_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setDebitAmt(String debitAmt) {
        this.debitAmt = debitAmt == null ? null : debitAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.CREDIT_AMT
     *
     * @return the value of QD_CBS_ACC_TXN.CREDIT_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getCreditAmt() {
        return creditAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.CREDIT_AMT
     *
     * @param creditAmt the value for QD_CBS_ACC_TXN.CREDIT_AMT
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setCreditAmt(String creditAmt) {
        this.creditAmt = creditAmt == null ? null : creditAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.TXN_TYPE
     *
     * @return the value of QD_CBS_ACC_TXN.TXN_TYPE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getTxnType() {
        return txnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.TXN_TYPE
     *
     * @param txnType the value for QD_CBS_ACC_TXN.TXN_TYPE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setTxnType(String txnType) {
        this.txnType = txnType == null ? null : txnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.TXN_SERIAL_NO
     *
     * @return the value of QD_CBS_ACC_TXN.TXN_SERIAL_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getTxnSerialNo() {
        return txnSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.TXN_SERIAL_NO
     *
     * @param txnSerialNo the value for QD_CBS_ACC_TXN.TXN_SERIAL_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setTxnSerialNo(String txnSerialNo) {
        this.txnSerialNo = txnSerialNo == null ? null : txnSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.SUMMARY_CODE
     *
     * @return the value of QD_CBS_ACC_TXN.SUMMARY_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getSummaryCode() {
        return summaryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.SUMMARY_CODE
     *
     * @param summaryCode the value for QD_CBS_ACC_TXN.SUMMARY_CODE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setSummaryCode(String summaryCode) {
        this.summaryCode = summaryCode == null ? null : summaryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.TXN_DATE
     *
     * @return the value of QD_CBS_ACC_TXN.TXN_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.TXN_DATE
     *
     * @param txnDate the value for QD_CBS_ACC_TXN.TXN_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.TXN_TIME
     *
     * @return the value of QD_CBS_ACC_TXN.TXN_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getTxnTime() {
        return txnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.TXN_TIME
     *
     * @param txnTime the value for QD_CBS_ACC_TXN.TXN_TIME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setTxnTime(String txnTime) {
        this.txnTime = txnTime == null ? null : txnTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.REMARK
     *
     * @return the value of QD_CBS_ACC_TXN.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.REMARK
     *
     * @param remark the value for QD_CBS_ACC_TXN.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.SEND_FLAG
     *
     * @return the value of QD_CBS_ACC_TXN.SEND_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getSendFlag() {
        return sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.SEND_FLAG
     *
     * @param sendFlag the value for QD_CBS_ACC_TXN.SEND_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setSendFlag(String sendFlag) {
        this.sendFlag = sendFlag == null ? null : sendFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_CBS_ACC_TXN.ACCOUNT_NAME
     *
     * @return the value of QD_CBS_ACC_TXN.ACCOUNT_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_CBS_ACC_TXN.ACCOUNT_NAME
     *
     * @param accountName the value for QD_CBS_ACC_TXN.ACCOUNT_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }
}