package rfm.qd.repository.model;

import java.util.Date;

public class QdRsFdccompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.COMPANY_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.COMPANY_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.COMPANY_SHRT_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String companyShrtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.MNGR_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String mngrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.ADDRESS
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.TRAD_LICENCE_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String tradLicenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private Integer modificationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.DELETE_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QD_RS_FDCCOMPANY.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.PK_ID
     *
     * @return the value of QD_RS_FDCCOMPANY.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.PK_ID
     *
     * @param pkId the value for QD_RS_FDCCOMPANY.PK_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setPkId(String pkId) {
        this.pkId = pkId == null ? null : pkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.COMPANY_ID
     *
     * @return the value of QD_RS_FDCCOMPANY.COMPANY_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.COMPANY_ID
     *
     * @param companyId the value for QD_RS_FDCCOMPANY.COMPANY_ID
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.COMPANY_NAME
     *
     * @return the value of QD_RS_FDCCOMPANY.COMPANY_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.COMPANY_NAME
     *
     * @param companyName the value for QD_RS_FDCCOMPANY.COMPANY_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.COMPANY_SHRT_NAME
     *
     * @return the value of QD_RS_FDCCOMPANY.COMPANY_SHRT_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getCompanyShrtName() {
        return companyShrtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.COMPANY_SHRT_NAME
     *
     * @param companyShrtName the value for QD_RS_FDCCOMPANY.COMPANY_SHRT_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setCompanyShrtName(String companyShrtName) {
        this.companyShrtName = companyShrtName == null ? null : companyShrtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.MNGR_NAME
     *
     * @return the value of QD_RS_FDCCOMPANY.MNGR_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getMngrName() {
        return mngrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.MNGR_NAME
     *
     * @param mngrName the value for QD_RS_FDCCOMPANY.MNGR_NAME
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setMngrName(String mngrName) {
        this.mngrName = mngrName == null ? null : mngrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.ADDRESS
     *
     * @return the value of QD_RS_FDCCOMPANY.ADDRESS
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.ADDRESS
     *
     * @param address the value for QD_RS_FDCCOMPANY.ADDRESS
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.TRAD_LICENCE_NO
     *
     * @return the value of QD_RS_FDCCOMPANY.TRAD_LICENCE_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getTradLicenceNo() {
        return tradLicenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.TRAD_LICENCE_NO
     *
     * @param tradLicenceNo the value for QD_RS_FDCCOMPANY.TRAD_LICENCE_NO
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setTradLicenceNo(String tradLicenceNo) {
        this.tradLicenceNo = tradLicenceNo == null ? null : tradLicenceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.CREATED_BY
     *
     * @return the value of QD_RS_FDCCOMPANY.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.CREATED_BY
     *
     * @param createdBy the value for QD_RS_FDCCOMPANY.CREATED_BY
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.CREATED_DATE
     *
     * @return the value of QD_RS_FDCCOMPANY.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.CREATED_DATE
     *
     * @param createdDate the value for QD_RS_FDCCOMPANY.CREATED_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.LAST_UPD_BY
     *
     * @return the value of QD_RS_FDCCOMPANY.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.LAST_UPD_BY
     *
     * @param lastUpdBy the value for QD_RS_FDCCOMPANY.LAST_UPD_BY
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.LAST_UPD_DATE
     *
     * @return the value of QD_RS_FDCCOMPANY.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for QD_RS_FDCCOMPANY.LAST_UPD_DATE
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.MODIFICATION_NUM
     *
     * @return the value of QD_RS_FDCCOMPANY.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public Integer getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.MODIFICATION_NUM
     *
     * @param modificationNum the value for QD_RS_FDCCOMPANY.MODIFICATION_NUM
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.DELETE_FLAG
     *
     * @return the value of QD_RS_FDCCOMPANY.DELETE_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.DELETE_FLAG
     *
     * @param deleteFlag the value for QD_RS_FDCCOMPANY.DELETE_FLAG
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QD_RS_FDCCOMPANY.REMARK
     *
     * @return the value of QD_RS_FDCCOMPANY.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QD_RS_FDCCOMPANY.REMARK
     *
     * @param remark the value for QD_RS_FDCCOMPANY.REMARK
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}