package rfm.qd.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class RsReceive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.PK_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.DOC_NO
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String docNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BUSINESS_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BUSINESS_NO
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String businessNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.COMPANY_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.COMPANY_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.ACCOUNT_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.ACCOUNT_CODE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BUYER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String buyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BUYER_CERT_TYPE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String buyerCertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BUYER_CERT_NO
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String buyerCertNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BUYER_ACC_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String buyerAccName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BUYER_ACC_CODE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String buyerAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BUYER_BANK_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String buyerBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.PURPOSE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.RECEIVE_TYPE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String receiveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.PL_AMOUNT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private BigDecimal plAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.AP_AMOUNT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private BigDecimal apAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BACK_DESC
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String backDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.SERIAL
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.BANK_SERIAL
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String bankSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.TRADE_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.TRADE_RESULT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String tradeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.STATUS_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String statusFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.STATUS_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String statusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.WORK_RESULT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String workResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.APPLY_USER_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String applyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.APPLY_USER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String applyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.APPLY_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.AUDIT_USER_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String auditUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.AUDIT_USER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String auditUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.AUDIT_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String auditDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.EXEC_USER_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String execUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.EXEC_USER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String execUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.EXEC_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String execDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.WF_INSTANCE_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String wfInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.ATTACH_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String attachFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.REMARK
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.DELETED_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.ORIGIN_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.ORIGIN_APP
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String originApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.CREATED_BY
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.CREATED_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.LAST_UPD_BY
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.LAST_UPD_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.MODIFICATION_NUM
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private Integer modificationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.TRADE_ACC_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String tradeAccName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.TRADE_ACC_CODE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String tradeAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BRZFDC.RS_RECEIVE.TRADE_BANK_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    private String tradeBankName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.PK_ID
     *
     * @return the value of BRZFDC.RS_RECEIVE.PK_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.PK_ID
     *
     * @param pkId the value for BRZFDC.RS_RECEIVE.PK_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setPkId(String pkId) {
        this.pkId = pkId == null ? null : pkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.DOC_NO
     *
     * @return the value of BRZFDC.RS_RECEIVE.DOC_NO
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getDocNo() {
        return docNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.DOC_NO
     *
     * @param docNo the value for BRZFDC.RS_RECEIVE.DOC_NO
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setDocNo(String docNo) {
        this.docNo = docNo == null ? null : docNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BUSINESS_ID
     *
     * @return the value of BRZFDC.RS_RECEIVE.BUSINESS_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BUSINESS_ID
     *
     * @param businessId the value for BRZFDC.RS_RECEIVE.BUSINESS_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BUSINESS_NO
     *
     * @return the value of BRZFDC.RS_RECEIVE.BUSINESS_NO
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBusinessNo() {
        return businessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BUSINESS_NO
     *
     * @param businessNo the value for BRZFDC.RS_RECEIVE.BUSINESS_NO
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBusinessNo(String businessNo) {
        this.businessNo = businessNo == null ? null : businessNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.COMPANY_ID
     *
     * @return the value of BRZFDC.RS_RECEIVE.COMPANY_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.COMPANY_ID
     *
     * @param companyId the value for BRZFDC.RS_RECEIVE.COMPANY_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.COMPANY_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.COMPANY_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.COMPANY_NAME
     *
     * @param companyName the value for BRZFDC.RS_RECEIVE.COMPANY_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.ACCOUNT_ID
     *
     * @return the value of BRZFDC.RS_RECEIVE.ACCOUNT_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.ACCOUNT_ID
     *
     * @param accountId the value for BRZFDC.RS_RECEIVE.ACCOUNT_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.ACCOUNT_CODE
     *
     * @return the value of BRZFDC.RS_RECEIVE.ACCOUNT_CODE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.ACCOUNT_CODE
     *
     * @param accountCode the value for BRZFDC.RS_RECEIVE.ACCOUNT_CODE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BUYER_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.BUYER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BUYER_NAME
     *
     * @param buyerName the value for BRZFDC.RS_RECEIVE.BUYER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BUYER_CERT_TYPE
     *
     * @return the value of BRZFDC.RS_RECEIVE.BUYER_CERT_TYPE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBuyerCertType() {
        return buyerCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BUYER_CERT_TYPE
     *
     * @param buyerCertType the value for BRZFDC.RS_RECEIVE.BUYER_CERT_TYPE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBuyerCertType(String buyerCertType) {
        this.buyerCertType = buyerCertType == null ? null : buyerCertType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BUYER_CERT_NO
     *
     * @return the value of BRZFDC.RS_RECEIVE.BUYER_CERT_NO
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBuyerCertNo() {
        return buyerCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BUYER_CERT_NO
     *
     * @param buyerCertNo the value for BRZFDC.RS_RECEIVE.BUYER_CERT_NO
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBuyerCertNo(String buyerCertNo) {
        this.buyerCertNo = buyerCertNo == null ? null : buyerCertNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BUYER_ACC_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.BUYER_ACC_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBuyerAccName() {
        return buyerAccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BUYER_ACC_NAME
     *
     * @param buyerAccName the value for BRZFDC.RS_RECEIVE.BUYER_ACC_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBuyerAccName(String buyerAccName) {
        this.buyerAccName = buyerAccName == null ? null : buyerAccName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BUYER_ACC_CODE
     *
     * @return the value of BRZFDC.RS_RECEIVE.BUYER_ACC_CODE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBuyerAccCode() {
        return buyerAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BUYER_ACC_CODE
     *
     * @param buyerAccCode the value for BRZFDC.RS_RECEIVE.BUYER_ACC_CODE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBuyerAccCode(String buyerAccCode) {
        this.buyerAccCode = buyerAccCode == null ? null : buyerAccCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BUYER_BANK_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.BUYER_BANK_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBuyerBankName() {
        return buyerBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BUYER_BANK_NAME
     *
     * @param buyerBankName the value for BRZFDC.RS_RECEIVE.BUYER_BANK_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBuyerBankName(String buyerBankName) {
        this.buyerBankName = buyerBankName == null ? null : buyerBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.PURPOSE
     *
     * @return the value of BRZFDC.RS_RECEIVE.PURPOSE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.PURPOSE
     *
     * @param purpose the value for BRZFDC.RS_RECEIVE.PURPOSE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.RECEIVE_TYPE
     *
     * @return the value of BRZFDC.RS_RECEIVE.RECEIVE_TYPE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getReceiveType() {
        return receiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.RECEIVE_TYPE
     *
     * @param receiveType the value for BRZFDC.RS_RECEIVE.RECEIVE_TYPE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setReceiveType(String receiveType) {
        this.receiveType = receiveType == null ? null : receiveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.PL_AMOUNT
     *
     * @return the value of BRZFDC.RS_RECEIVE.PL_AMOUNT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public BigDecimal getPlAmount() {
        return plAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.PL_AMOUNT
     *
     * @param plAmount the value for BRZFDC.RS_RECEIVE.PL_AMOUNT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setPlAmount(BigDecimal plAmount) {
        this.plAmount = plAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.AP_AMOUNT
     *
     * @return the value of BRZFDC.RS_RECEIVE.AP_AMOUNT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public BigDecimal getApAmount() {
        return apAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.AP_AMOUNT
     *
     * @param apAmount the value for BRZFDC.RS_RECEIVE.AP_AMOUNT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setApAmount(BigDecimal apAmount) {
        this.apAmount = apAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BACK_DESC
     *
     * @return the value of BRZFDC.RS_RECEIVE.BACK_DESC
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBackDesc() {
        return backDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BACK_DESC
     *
     * @param backDesc the value for BRZFDC.RS_RECEIVE.BACK_DESC
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBackDesc(String backDesc) {
        this.backDesc = backDesc == null ? null : backDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.SERIAL
     *
     * @return the value of BRZFDC.RS_RECEIVE.SERIAL
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.SERIAL
     *
     * @param serial the value for BRZFDC.RS_RECEIVE.SERIAL
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.BANK_SERIAL
     *
     * @return the value of BRZFDC.RS_RECEIVE.BANK_SERIAL
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getBankSerial() {
        return bankSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.BANK_SERIAL
     *
     * @param bankSerial the value for BRZFDC.RS_RECEIVE.BANK_SERIAL
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setBankSerial(String bankSerial) {
        this.bankSerial = bankSerial == null ? null : bankSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.TRADE_DATE
     *
     * @return the value of BRZFDC.RS_RECEIVE.TRADE_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.TRADE_DATE
     *
     * @param tradeDate the value for BRZFDC.RS_RECEIVE.TRADE_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate == null ? null : tradeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.TRADE_RESULT
     *
     * @return the value of BRZFDC.RS_RECEIVE.TRADE_RESULT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getTradeResult() {
        return tradeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.TRADE_RESULT
     *
     * @param tradeResult the value for BRZFDC.RS_RECEIVE.TRADE_RESULT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setTradeResult(String tradeResult) {
        this.tradeResult = tradeResult == null ? null : tradeResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.STATUS_FLAG
     *
     * @return the value of BRZFDC.RS_RECEIVE.STATUS_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getStatusFlag() {
        return statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.STATUS_FLAG
     *
     * @param statusFlag the value for BRZFDC.RS_RECEIVE.STATUS_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setStatusFlag(String statusFlag) {
        this.statusFlag = statusFlag == null ? null : statusFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.STATUS_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.STATUS_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.STATUS_NAME
     *
     * @param statusName the value for BRZFDC.RS_RECEIVE.STATUS_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.WORK_RESULT
     *
     * @return the value of BRZFDC.RS_RECEIVE.WORK_RESULT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getWorkResult() {
        return workResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.WORK_RESULT
     *
     * @param workResult the value for BRZFDC.RS_RECEIVE.WORK_RESULT
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setWorkResult(String workResult) {
        this.workResult = workResult == null ? null : workResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.APPLY_USER_ID
     *
     * @return the value of BRZFDC.RS_RECEIVE.APPLY_USER_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getApplyUserId() {
        return applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.APPLY_USER_ID
     *
     * @param applyUserId the value for BRZFDC.RS_RECEIVE.APPLY_USER_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setApplyUserId(String applyUserId) {
        this.applyUserId = applyUserId == null ? null : applyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.APPLY_USER_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.APPLY_USER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getApplyUserName() {
        return applyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.APPLY_USER_NAME
     *
     * @param applyUserName the value for BRZFDC.RS_RECEIVE.APPLY_USER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setApplyUserName(String applyUserName) {
        this.applyUserName = applyUserName == null ? null : applyUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.APPLY_DATE
     *
     * @return the value of BRZFDC.RS_RECEIVE.APPLY_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.APPLY_DATE
     *
     * @param applyDate the value for BRZFDC.RS_RECEIVE.APPLY_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate == null ? null : applyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.AUDIT_USER_ID
     *
     * @return the value of BRZFDC.RS_RECEIVE.AUDIT_USER_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getAuditUserId() {
        return auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.AUDIT_USER_ID
     *
     * @param auditUserId the value for BRZFDC.RS_RECEIVE.AUDIT_USER_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId == null ? null : auditUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.AUDIT_USER_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.AUDIT_USER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getAuditUserName() {
        return auditUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.AUDIT_USER_NAME
     *
     * @param auditUserName the value for BRZFDC.RS_RECEIVE.AUDIT_USER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setAuditUserName(String auditUserName) {
        this.auditUserName = auditUserName == null ? null : auditUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.AUDIT_DATE
     *
     * @return the value of BRZFDC.RS_RECEIVE.AUDIT_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.AUDIT_DATE
     *
     * @param auditDate the value for BRZFDC.RS_RECEIVE.AUDIT_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setAuditDate(String auditDate) {
        this.auditDate = auditDate == null ? null : auditDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.EXEC_USER_ID
     *
     * @return the value of BRZFDC.RS_RECEIVE.EXEC_USER_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getExecUserId() {
        return execUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.EXEC_USER_ID
     *
     * @param execUserId the value for BRZFDC.RS_RECEIVE.EXEC_USER_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setExecUserId(String execUserId) {
        this.execUserId = execUserId == null ? null : execUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.EXEC_USER_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.EXEC_USER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getExecUserName() {
        return execUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.EXEC_USER_NAME
     *
     * @param execUserName the value for BRZFDC.RS_RECEIVE.EXEC_USER_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setExecUserName(String execUserName) {
        this.execUserName = execUserName == null ? null : execUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.EXEC_DATE
     *
     * @return the value of BRZFDC.RS_RECEIVE.EXEC_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getExecDate() {
        return execDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.EXEC_DATE
     *
     * @param execDate the value for BRZFDC.RS_RECEIVE.EXEC_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setExecDate(String execDate) {
        this.execDate = execDate == null ? null : execDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.WF_INSTANCE_ID
     *
     * @return the value of BRZFDC.RS_RECEIVE.WF_INSTANCE_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getWfInstanceId() {
        return wfInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.WF_INSTANCE_ID
     *
     * @param wfInstanceId the value for BRZFDC.RS_RECEIVE.WF_INSTANCE_ID
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setWfInstanceId(String wfInstanceId) {
        this.wfInstanceId = wfInstanceId == null ? null : wfInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.ATTACH_FLAG
     *
     * @return the value of BRZFDC.RS_RECEIVE.ATTACH_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getAttachFlag() {
        return attachFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.ATTACH_FLAG
     *
     * @param attachFlag the value for BRZFDC.RS_RECEIVE.ATTACH_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setAttachFlag(String attachFlag) {
        this.attachFlag = attachFlag == null ? null : attachFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.REMARK
     *
     * @return the value of BRZFDC.RS_RECEIVE.REMARK
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.REMARK
     *
     * @param remark the value for BRZFDC.RS_RECEIVE.REMARK
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.DELETED_FLAG
     *
     * @return the value of BRZFDC.RS_RECEIVE.DELETED_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.DELETED_FLAG
     *
     * @param deletedFlag the value for BRZFDC.RS_RECEIVE.DELETED_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.ORIGIN_FLAG
     *
     * @return the value of BRZFDC.RS_RECEIVE.ORIGIN_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.ORIGIN_FLAG
     *
     * @param originFlag the value for BRZFDC.RS_RECEIVE.ORIGIN_FLAG
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.ORIGIN_APP
     *
     * @return the value of BRZFDC.RS_RECEIVE.ORIGIN_APP
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getOriginApp() {
        return originApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.ORIGIN_APP
     *
     * @param originApp the value for BRZFDC.RS_RECEIVE.ORIGIN_APP
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setOriginApp(String originApp) {
        this.originApp = originApp == null ? null : originApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.CREATED_BY
     *
     * @return the value of BRZFDC.RS_RECEIVE.CREATED_BY
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.CREATED_BY
     *
     * @param createdBy the value for BRZFDC.RS_RECEIVE.CREATED_BY
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.CREATED_DATE
     *
     * @return the value of BRZFDC.RS_RECEIVE.CREATED_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.CREATED_DATE
     *
     * @param createdDate the value for BRZFDC.RS_RECEIVE.CREATED_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.LAST_UPD_BY
     *
     * @return the value of BRZFDC.RS_RECEIVE.LAST_UPD_BY
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.LAST_UPD_BY
     *
     * @param lastUpdBy the value for BRZFDC.RS_RECEIVE.LAST_UPD_BY
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.LAST_UPD_DATE
     *
     * @return the value of BRZFDC.RS_RECEIVE.LAST_UPD_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for BRZFDC.RS_RECEIVE.LAST_UPD_DATE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.MODIFICATION_NUM
     *
     * @return the value of BRZFDC.RS_RECEIVE.MODIFICATION_NUM
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public Integer getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.MODIFICATION_NUM
     *
     * @param modificationNum the value for BRZFDC.RS_RECEIVE.MODIFICATION_NUM
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setModificationNum(Integer modificationNum) {
        this.modificationNum = modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.TRADE_ACC_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.TRADE_ACC_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getTradeAccName() {
        return tradeAccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.TRADE_ACC_NAME
     *
     * @param tradeAccName the value for BRZFDC.RS_RECEIVE.TRADE_ACC_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setTradeAccName(String tradeAccName) {
        this.tradeAccName = tradeAccName == null ? null : tradeAccName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.TRADE_ACC_CODE
     *
     * @return the value of BRZFDC.RS_RECEIVE.TRADE_ACC_CODE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getTradeAccCode() {
        return tradeAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.TRADE_ACC_CODE
     *
     * @param tradeAccCode the value for BRZFDC.RS_RECEIVE.TRADE_ACC_CODE
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setTradeAccCode(String tradeAccCode) {
        this.tradeAccCode = tradeAccCode == null ? null : tradeAccCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRZFDC.RS_RECEIVE.TRADE_BANK_NAME
     *
     * @return the value of BRZFDC.RS_RECEIVE.TRADE_BANK_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public String getTradeBankName() {
        return tradeBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRZFDC.RS_RECEIVE.TRADE_BANK_NAME
     *
     * @param tradeBankName the value for BRZFDC.RS_RECEIVE.TRADE_BANK_NAME
     *
     * @mbggenerated Wed Sep 07 18:29:53 CST 2011
     */
    public void setTradeBankName(String tradeBankName) {
        this.tradeBankName = tradeBankName == null ? null : tradeBankName.trim();
    }
}