package rfm.qd.repository.model;

import java.util.ArrayList;
import java.util.List;

public class RsSendLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public RsSendLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andSysDateIsNull() {
            addCriterion("SYS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSysDateIsNotNull() {
            addCriterion("SYS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSysDateEqualTo(String value) {
            addCriterion("SYS_DATE =", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateNotEqualTo(String value) {
            addCriterion("SYS_DATE <>", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateGreaterThan(String value) {
            addCriterion("SYS_DATE >", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_DATE >=", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateLessThan(String value) {
            addCriterion("SYS_DATE <", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateLessThanOrEqualTo(String value) {
            addCriterion("SYS_DATE <=", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateLike(String value) {
            addCriterion("SYS_DATE like", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateNotLike(String value) {
            addCriterion("SYS_DATE not like", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateIn(List<String> values) {
            addCriterion("SYS_DATE in", values, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateNotIn(List<String> values) {
            addCriterion("SYS_DATE not in", values, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateBetween(String value1, String value2) {
            addCriterion("SYS_DATE between", value1, value2, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateNotBetween(String value1, String value2) {
            addCriterion("SYS_DATE not between", value1, value2, "sysDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNull() {
            addCriterion("TXN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNotNull() {
            addCriterion("TXN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnDateEqualTo(String value) {
            addCriterion("TXN_DATE =", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotEqualTo(String value) {
            addCriterion("TXN_DATE <>", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThan(String value) {
            addCriterion("TXN_DATE >", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_DATE >=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThan(String value) {
            addCriterion("TXN_DATE <", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThanOrEqualTo(String value) {
            addCriterion("TXN_DATE <=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLike(String value) {
            addCriterion("TXN_DATE like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotLike(String value) {
            addCriterion("TXN_DATE not like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateIn(List<String> values) {
            addCriterion("TXN_DATE in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotIn(List<String> values) {
            addCriterion("TXN_DATE not in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateBetween(String value1, String value2) {
            addCriterion("TXN_DATE between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotBetween(String value1, String value2) {
            addCriterion("TXN_DATE not between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnNamIsNull() {
            addCriterion("TXN_NAM is null");
            return (Criteria) this;
        }

        public Criteria andTxnNamIsNotNull() {
            addCriterion("TXN_NAM is not null");
            return (Criteria) this;
        }

        public Criteria andTxnNamEqualTo(String value) {
            addCriterion("TXN_NAM =", value, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamNotEqualTo(String value) {
            addCriterion("TXN_NAM <>", value, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamGreaterThan(String value) {
            addCriterion("TXN_NAM >", value, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_NAM >=", value, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamLessThan(String value) {
            addCriterion("TXN_NAM <", value, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamLessThanOrEqualTo(String value) {
            addCriterion("TXN_NAM <=", value, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamLike(String value) {
            addCriterion("TXN_NAM like", value, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamNotLike(String value) {
            addCriterion("TXN_NAM not like", value, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamIn(List<String> values) {
            addCriterion("TXN_NAM in", values, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamNotIn(List<String> values) {
            addCriterion("TXN_NAM not in", values, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamBetween(String value1, String value2) {
            addCriterion("TXN_NAM between", value1, value2, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnNamNotBetween(String value1, String value2) {
            addCriterion("TXN_NAM not between", value1, value2, "txnNam");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNull() {
            addCriterion("TXN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNotNull() {
            addCriterion("TXN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeEqualTo(String value) {
            addCriterion("TXN_CODE =", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotEqualTo(String value) {
            addCriterion("TXN_CODE <>", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThan(String value) {
            addCriterion("TXN_CODE >", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_CODE >=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThan(String value) {
            addCriterion("TXN_CODE <", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThanOrEqualTo(String value) {
            addCriterion("TXN_CODE <=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLike(String value) {
            addCriterion("TXN_CODE like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotLike(String value) {
            addCriterion("TXN_CODE not like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIn(List<String> values) {
            addCriterion("TXN_CODE in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotIn(List<String> values) {
            addCriterion("TXN_CODE not in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeBetween(String value1, String value2) {
            addCriterion("TXN_CODE between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotBetween(String value1, String value2) {
            addCriterion("TXN_CODE not between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnResultIsNull() {
            addCriterion("TXN_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andTxnResultIsNotNull() {
            addCriterion("TXN_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andTxnResultEqualTo(String value) {
            addCriterion("TXN_RESULT =", value, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultNotEqualTo(String value) {
            addCriterion("TXN_RESULT <>", value, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultGreaterThan(String value) {
            addCriterion("TXN_RESULT >", value, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_RESULT >=", value, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultLessThan(String value) {
            addCriterion("TXN_RESULT <", value, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultLessThanOrEqualTo(String value) {
            addCriterion("TXN_RESULT <=", value, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultLike(String value) {
            addCriterion("TXN_RESULT like", value, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultNotLike(String value) {
            addCriterion("TXN_RESULT not like", value, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultIn(List<String> values) {
            addCriterion("TXN_RESULT in", values, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultNotIn(List<String> values) {
            addCriterion("TXN_RESULT not in", values, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultBetween(String value1, String value2) {
            addCriterion("TXN_RESULT between", value1, value2, "txnResult");
            return (Criteria) this;
        }

        public Criteria andTxnResultNotBetween(String value1, String value2) {
            addCriterion("TXN_RESULT not between", value1, value2, "txnResult");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andFiller10IsNull() {
            addCriterion("FILLER10 is null");
            return (Criteria) this;
        }

        public Criteria andFiller10IsNotNull() {
            addCriterion("FILLER10 is not null");
            return (Criteria) this;
        }

        public Criteria andFiller10EqualTo(String value) {
            addCriterion("FILLER10 =", value, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10NotEqualTo(String value) {
            addCriterion("FILLER10 <>", value, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10GreaterThan(String value) {
            addCriterion("FILLER10 >", value, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10GreaterThanOrEqualTo(String value) {
            addCriterion("FILLER10 >=", value, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10LessThan(String value) {
            addCriterion("FILLER10 <", value, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10LessThanOrEqualTo(String value) {
            addCriterion("FILLER10 <=", value, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10Like(String value) {
            addCriterion("FILLER10 like", value, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10NotLike(String value) {
            addCriterion("FILLER10 not like", value, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10In(List<String> values) {
            addCriterion("FILLER10 in", values, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10NotIn(List<String> values) {
            addCriterion("FILLER10 not in", values, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10Between(String value1, String value2) {
            addCriterion("FILLER10 between", value1, value2, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller10NotBetween(String value1, String value2) {
            addCriterion("FILLER10 not between", value1, value2, "filler10");
            return (Criteria) this;
        }

        public Criteria andFiller40IsNull() {
            addCriterion("FILLER40 is null");
            return (Criteria) this;
        }

        public Criteria andFiller40IsNotNull() {
            addCriterion("FILLER40 is not null");
            return (Criteria) this;
        }

        public Criteria andFiller40EqualTo(String value) {
            addCriterion("FILLER40 =", value, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40NotEqualTo(String value) {
            addCriterion("FILLER40 <>", value, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40GreaterThan(String value) {
            addCriterion("FILLER40 >", value, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40GreaterThanOrEqualTo(String value) {
            addCriterion("FILLER40 >=", value, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40LessThan(String value) {
            addCriterion("FILLER40 <", value, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40LessThanOrEqualTo(String value) {
            addCriterion("FILLER40 <=", value, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40Like(String value) {
            addCriterion("FILLER40 like", value, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40NotLike(String value) {
            addCriterion("FILLER40 not like", value, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40In(List<String> values) {
            addCriterion("FILLER40 in", values, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40NotIn(List<String> values) {
            addCriterion("FILLER40 not in", values, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40Between(String value1, String value2) {
            addCriterion("FILLER40 between", value1, value2, "filler40");
            return (Criteria) this;
        }

        public Criteria andFiller40NotBetween(String value1, String value2) {
            addCriterion("FILLER40 not between", value1, value2, "filler40");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 30 15:52:14 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BRZFDC.RS_SEND_LOG
     *
     * @mbggenerated Mon Apr 30 15:52:14 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}