package rfm.qd.repository.model;

import java.util.ArrayList;
import java.util.List;

public class RsSysCtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public RsSysCtlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysNoIsNull() {
            addCriterion("SYS_NO is null");
            return (Criteria) this;
        }

        public Criteria andSysNoIsNotNull() {
            addCriterion("SYS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoEqualTo(String value) {
            addCriterion("SYS_NO =", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoNotEqualTo(String value) {
            addCriterion("SYS_NO <>", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoGreaterThan(String value) {
            addCriterion("SYS_NO >", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_NO >=", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoLessThan(String value) {
            addCriterion("SYS_NO <", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoLessThanOrEqualTo(String value) {
            addCriterion("SYS_NO <=", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoLike(String value) {
            addCriterion("SYS_NO like", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoNotLike(String value) {
            addCriterion("SYS_NO not like", value, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoIn(List<String> values) {
            addCriterion("SYS_NO in", values, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoNotIn(List<String> values) {
            addCriterion("SYS_NO not in", values, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoBetween(String value1, String value2) {
            addCriterion("SYS_NO between", value1, value2, "sysNo");
            return (Criteria) this;
        }

        public Criteria andSysNoNotBetween(String value1, String value2) {
            addCriterion("SYS_NO not between", value1, value2, "sysNo");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNull() {
            addCriterion("BANK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNotNull() {
            addCriterion("BANK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBankIdEqualTo(String value) {
            addCriterion("BANK_ID =", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotEqualTo(String value) {
            addCriterion("BANK_ID <>", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThan(String value) {
            addCriterion("BANK_ID >", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_ID >=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThan(String value) {
            addCriterion("BANK_ID <", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThanOrEqualTo(String value) {
            addCriterion("BANK_ID <=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLike(String value) {
            addCriterion("BANK_ID like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotLike(String value) {
            addCriterion("BANK_ID not like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdIn(List<String> values) {
            addCriterion("BANK_ID in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotIn(List<String> values) {
            addCriterion("BANK_ID not in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdBetween(String value1, String value2) {
            addCriterion("BANK_ID between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotBetween(String value1, String value2) {
            addCriterion("BANK_ID not between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andSysDateIsNull() {
            addCriterion("SYS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSysDateIsNotNull() {
            addCriterion("SYS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSysDateEqualTo(String value) {
            addCriterion("SYS_DATE =", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateNotEqualTo(String value) {
            addCriterion("SYS_DATE <>", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateGreaterThan(String value) {
            addCriterion("SYS_DATE >", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_DATE >=", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateLessThan(String value) {
            addCriterion("SYS_DATE <", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateLessThanOrEqualTo(String value) {
            addCriterion("SYS_DATE <=", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateLike(String value) {
            addCriterion("SYS_DATE like", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateNotLike(String value) {
            addCriterion("SYS_DATE not like", value, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateIn(List<String> values) {
            addCriterion("SYS_DATE in", values, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateNotIn(List<String> values) {
            addCriterion("SYS_DATE not in", values, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateBetween(String value1, String value2) {
            addCriterion("SYS_DATE between", value1, value2, "sysDate");
            return (Criteria) this;
        }

        public Criteria andSysDateNotBetween(String value1, String value2) {
            addCriterion("SYS_DATE not between", value1, value2, "sysDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateIsNull() {
            addCriterion("LAST_SEND_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastSendDateIsNotNull() {
            addCriterion("LAST_SEND_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastSendDateEqualTo(String value) {
            addCriterion("LAST_SEND_DATE =", value, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateNotEqualTo(String value) {
            addCriterion("LAST_SEND_DATE <>", value, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateGreaterThan(String value) {
            addCriterion("LAST_SEND_DATE >", value, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_SEND_DATE >=", value, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateLessThan(String value) {
            addCriterion("LAST_SEND_DATE <", value, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateLessThanOrEqualTo(String value) {
            addCriterion("LAST_SEND_DATE <=", value, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateLike(String value) {
            addCriterion("LAST_SEND_DATE like", value, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateNotLike(String value) {
            addCriterion("LAST_SEND_DATE not like", value, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateIn(List<String> values) {
            addCriterion("LAST_SEND_DATE in", values, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateNotIn(List<String> values) {
            addCriterion("LAST_SEND_DATE not in", values, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateBetween(String value1, String value2) {
            addCriterion("LAST_SEND_DATE between", value1, value2, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andLastSendDateNotBetween(String value1, String value2) {
            addCriterion("LAST_SEND_DATE not between", value1, value2, "lastSendDate");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNull() {
            addCriterion("SEQ_NO is null");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNotNull() {
            addCriterion("SEQ_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNoEqualTo(Integer value) {
            addCriterion("SEQ_NO =", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotEqualTo(Integer value) {
            addCriterion("SEQ_NO <>", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThan(Integer value) {
            addCriterion("SEQ_NO >", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQ_NO >=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThan(Integer value) {
            addCriterion("SEQ_NO <", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThanOrEqualTo(Integer value) {
            addCriterion("SEQ_NO <=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoIn(List<Integer> values) {
            addCriterion("SEQ_NO in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotIn(List<Integer> values) {
            addCriterion("SEQ_NO not in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_NO between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_NO not between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateIsNull() {
            addCriterion("LAST_GETTXN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateIsNotNull() {
            addCriterion("LAST_GETTXN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateEqualTo(String value) {
            addCriterion("LAST_GETTXN_DATE =", value, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateNotEqualTo(String value) {
            addCriterion("LAST_GETTXN_DATE <>", value, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateGreaterThan(String value) {
            addCriterion("LAST_GETTXN_DATE >", value, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_GETTXN_DATE >=", value, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateLessThan(String value) {
            addCriterion("LAST_GETTXN_DATE <", value, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateLessThanOrEqualTo(String value) {
            addCriterion("LAST_GETTXN_DATE <=", value, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateLike(String value) {
            addCriterion("LAST_GETTXN_DATE like", value, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateNotLike(String value) {
            addCriterion("LAST_GETTXN_DATE not like", value, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateIn(List<String> values) {
            addCriterion("LAST_GETTXN_DATE in", values, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateNotIn(List<String> values) {
            addCriterion("LAST_GETTXN_DATE not in", values, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateBetween(String value1, String value2) {
            addCriterion("LAST_GETTXN_DATE between", value1, value2, "lastGettxnDate");
            return (Criteria) this;
        }

        public Criteria andLastGettxnDateNotBetween(String value1, String value2) {
            addCriterion("LAST_GETTXN_DATE not between", value1, value2, "lastGettxnDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 30 13:30:08 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}