package rfm.qd.repository.dao;

import rfm.qd.repository.model.BiAccountDetail;
import rfm.qd.repository.model.BiAccountDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BiAccountDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int countByExample(BiAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int deleteByExample(BiAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int insert(BiAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int insertSelective(BiAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    List<BiAccountDetail> selectByExample(BiAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    BiAccountDetail selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int updateByExampleSelective(@Param("record") BiAccountDetail record, @Param("example") BiAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int updateByExample(@Param("record") BiAccountDetail record, @Param("example") BiAccountDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int updateByPrimaryKeySelective(BiAccountDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_ACCOUNT_DETAIL
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int updateByPrimaryKey(BiAccountDetail record);
}