package rfm.qd.repository.dao;

import rfm.qd.repository.model.BiTradeLog;
import rfm.qd.repository.model.BiTradeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BiTradeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int countByExample(BiTradeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int deleteByExample(BiTradeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int insert(BiTradeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int insertSelective(BiTradeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    List<BiTradeLog> selectByExample(BiTradeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    BiTradeLog selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int updateByExampleSelective(@Param("record") BiTradeLog record, @Param("example") BiTradeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int updateByExample(@Param("record") BiTradeLog record, @Param("example") BiTradeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int updateByPrimaryKeySelective(BiTradeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.BI_TRADE_LOG
     *
     * @mbggenerated Wed Sep 07 18:28:59 CST 2011
     */
    int updateByPrimaryKey(BiTradeLog record);
}