package rfm.qd.repository.dao;

import rfm.qd.repository.model.CbsBankInfo;
import rfm.qd.repository.model.CbsBankInfoExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CbsBankInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.CBS_BANK_INFO
     *
     * @mbggenerated Tue May 08 15:57:37 CST 2012
     */
    int countByExample(CbsBankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.CBS_BANK_INFO
     *
     * @mbggenerated Tue May 08 15:57:37 CST 2012
     */
    int deleteByExample(CbsBankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.CBS_BANK_INFO
     *
     * @mbggenerated Tue May 08 15:57:37 CST 2012
     */
    int insert(CbsBankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.CBS_BANK_INFO
     *
     * @mbggenerated Tue May 08 15:57:37 CST 2012
     */
    int insertSelective(CbsBankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.CBS_BANK_INFO
     *
     * @mbggenerated Tue May 08 15:57:37 CST 2012
     */
    List<CbsBankInfo> selectByExample(CbsBankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.CBS_BANK_INFO
     *
     * @mbggenerated Tue May 08 15:57:37 CST 2012
     */
    int updateByExampleSelective(@Param("record") CbsBankInfo record, @Param("example") CbsBankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.CBS_BANK_INFO
     *
     * @mbggenerated Tue May 08 15:57:37 CST 2012
     */
    int updateByExample(@Param("record") CbsBankInfo record, @Param("example") CbsBankInfoExample example);
}