package rfm.qd.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import rfm.qd.repository.model.QdBiNotifyConf;
import rfm.qd.repository.model.QdBiNotifyConfExample;

public interface QdBiNotifyConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int countByExample(QdBiNotifyConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int deleteByExample(QdBiNotifyConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int insert(QdBiNotifyConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int insertSelective(QdBiNotifyConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    List<QdBiNotifyConf> selectByExample(QdBiNotifyConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    QdBiNotifyConf selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") QdBiNotifyConf record, @Param("example") QdBiNotifyConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByExample(@Param("record") QdBiNotifyConf record, @Param("example") QdBiNotifyConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByPrimaryKeySelective(QdBiNotifyConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_NOTIFY_CONF
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByPrimaryKey(QdBiNotifyConf record);
}