package rfm.qd.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import rfm.qd.repository.model.QdBiAccountBalance;
import rfm.qd.repository.model.QdBiAccountBalanceExample;

public interface QdBiAccountBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int countByExample(QdBiAccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int deleteByExample(QdBiAccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int insert(QdBiAccountBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int insertSelective(QdBiAccountBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    List<QdBiAccountBalance> selectByExample(QdBiAccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    QdBiAccountBalance selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") QdBiAccountBalance record, @Param("example") QdBiAccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByExample(@Param("record") QdBiAccountBalance record, @Param("example") QdBiAccountBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByPrimaryKeySelective(QdBiAccountBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_BI_ACCOUNT_BALANCE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByPrimaryKey(QdBiAccountBalance record);
}