package rfm.qd.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import rfm.qd.repository.model.QdRsReceive;
import rfm.qd.repository.model.QdRsReceiveExample;

public interface QdRsReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int countByExample(QdRsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int deleteByExample(QdRsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int insert(QdRsReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int insertSelective(QdRsReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    List<QdRsReceive> selectByExample(QdRsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    QdRsReceive selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") QdRsReceive record, @Param("example") QdRsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByExample(@Param("record") QdRsReceive record, @Param("example") QdRsReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByPrimaryKeySelective(QdRsReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_RECEIVE
     *
     * @mbggenerated Thu Jun 25 14:54:01 CST 2015
     */
    int updateByPrimaryKey(QdRsReceive record);
}