package rfm.qd.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import rfm.qd.repository.model.QdRsAccDetail;
import rfm.qd.repository.model.QdRsAccDetailExample;

public interface QdRsAccDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    int countByExample(QdRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    int deleteByExample(QdRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    int insert(QdRsAccDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    int insertSelective(QdRsAccDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    List<QdRsAccDetail> selectByExample(QdRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    QdRsAccDetail selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    int updateByExampleSelective(@Param("record") QdRsAccDetail record, @Param("example") QdRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    int updateByExample(@Param("record") QdRsAccDetail record, @Param("example") QdRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    int updateByPrimaryKeySelective(QdRsAccDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QD_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 14:54:00 CST 2015
     */
    int updateByPrimaryKey(QdRsAccDetail record);
}