package rfm.qd.repository.dao;

import rfm.qd.repository.model.RsContract;
import rfm.qd.repository.model.RsContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RsContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    int countByExample(RsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    int deleteByExample(RsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    int insert(RsContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    int insertSelective(RsContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    List<RsContract> selectByExample(RsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    RsContract selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    int updateByExampleSelective(@Param("record") RsContract record, @Param("example") RsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    int updateByExample(@Param("record") RsContract record, @Param("example") RsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    int updateByPrimaryKeySelective(RsContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_CONTRACT
     *
     * @mbggenerated Mon Aug 29 15:43:41 CST 2011
     */
    int updateByPrimaryKey(RsContract record);
}