package rfm.qd.repository.dao;

import rfm.qd.repository.model.RsSysCtl;
import rfm.qd.repository.model.RsSysCtlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RsSysCtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    int countByExample(RsSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    int deleteByExample(RsSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    int deleteByPrimaryKey(String sysNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    int insert(RsSysCtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    int insertSelective(RsSysCtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    List<RsSysCtl> selectByExample(RsSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    RsSysCtl selectByPrimaryKey(String sysNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    int updateByExampleSelective(@Param("record") RsSysCtl record, @Param("example") RsSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    int updateByExample(@Param("record") RsSysCtl record, @Param("example") RsSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    int updateByPrimaryKeySelective(RsSysCtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BRZFDC.RS_SYS_CTL
     *
     * @mbggenerated Mon Apr 30 13:30:08 CST 2012
     */
    int updateByPrimaryKey(RsSysCtl record);
}