package rfm.ta.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import rfm.ta.repository.model.TaRsSendLog;
import rfm.ta.repository.model.TaRsSendLogExample;
@Component
public interface TaRsSendLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int countByExample(TaRsSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int deleteByExample(TaRsSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int insert(TaRsSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int insertSelective(TaRsSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    List<TaRsSendLog> selectByExample(TaRsSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    TaRsSendLog selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") TaRsSendLog record, @Param("example") TaRsSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByExample(@Param("record") TaRsSendLog record, @Param("example") TaRsSendLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByPrimaryKeySelective(TaRsSendLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_SEND_LOG
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByPrimaryKey(TaRsSendLog record);
}