package rfm.ta.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import rfm.ta.repository.model.TaRsAccDetail;
import rfm.ta.repository.model.TaRsAccDetailExample;
@Component
public interface TaRsAccDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int countByExample(TaRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int deleteByExample(TaRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int deleteByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int insert(TaRsAccDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int insertSelective(TaRsAccDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    List<TaRsAccDetail> selectByExample(TaRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    TaRsAccDetail selectByPrimaryKey(String pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") TaRsAccDetail record, @Param("example") TaRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByExample(@Param("record") TaRsAccDetail record, @Param("example") TaRsAccDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByPrimaryKeySelective(TaRsAccDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_ACC_DETAIL
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByPrimaryKey(TaRsAccDetail record);
}