package rfm.ta.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import rfm.ta.repository.model.TaRsCheck;
import rfm.ta.repository.model.TaRsCheckExample;
@Component
public interface TaRsCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_CHECK
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int countByExample(TaRsCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_CHECK
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int deleteByExample(TaRsCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_CHECK
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int insert(TaRsCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_CHECK
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int insertSelective(TaRsCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_CHECK
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    List<TaRsCheck> selectByExample(TaRsCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_CHECK
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") TaRsCheck record, @Param("example") TaRsCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_RS_CHECK
     *
     * @mbggenerated Thu Jun 25 18:38:24 CST 2015
     */
    int updateByExample(@Param("record") TaRsCheck record, @Param("example") TaRsCheckExample example);
}